In [1]:
import numpy as np
import math

In [2]:
A = np.matrix([
    [2,1,1],
    [3,2,3],
    [1,4,9]
])

b = np.matrix([
    [10],
    [18],
    [16]
]) 

In [3]:
print(A)

[[2 1 1]
 [3 2 3]
 [1 4 9]]


In [4]:
print(b)

[[10]
 [18]
 [16]]


In [5]:
A = np.matrix([
    [4,-2,1],
    [1,1,1],
    [9,3,1]
])

b = np.matrix([
    [8],
    [-13],
    [3]
]) 

In [6]:
print(A)

[[ 4 -2  1]
 [ 1  1  1]
 [ 9  3  1]]


In [7]:
print(b)

[[  8]
 [-13]
 [  3]]


In [8]:
Ab = np.append(A,b,axis=1)
print(Ab)

[[  4  -2   1   8]
 [  1   1   1 -13]
 [  9   3   1   3]]


In [9]:
Ab[1,:]

matrix([[  1,   1,   1, -13]])

In [10]:
Ab[0,:]

matrix([[ 4, -2,  1,  8]])

In [11]:
Ab[0,1:2]

matrix([[-2]])

In [12]:
Ab[0,1:3]

matrix([[-2,  1]])

In [13]:
Ab[0:]

matrix([[  4,  -2,   1,   8],
        [  1,   1,   1, -13],
        [  9,   3,   1,   3]])

In [14]:
Ab[0,:]

matrix([[ 4, -2,  1,  8]])

In [15]:
Ab[1,:]

matrix([[  1,   1,   1, -13]])

In [16]:
Ab[1,:] = Ab[0,:] - Ab[1,:]

In [17]:
Ab

matrix([[ 4, -2,  1,  8],
        [ 3, -3,  0, 21],
        [ 9,  3,  1,  3]])

In [18]:
Ab[1,:] = Ab[1,:]/3

In [19]:
Ab

matrix([[ 4, -2,  1,  8],
        [ 1, -1,  0,  7],
        [ 9,  3,  1,  3]])

In [20]:
Ab[2,:] = Ab[2,:] - Ab[0,:]

In [21]:
Ab

matrix([[ 4, -2,  1,  8],
        [ 1, -1,  0,  7],
        [ 5,  5,  0, -5]])

In [22]:
Ab[2,:] = Ab[2,:]/5

In [23]:
Ab

matrix([[ 4, -2,  1,  8],
        [ 1, -1,  0,  7],
        [ 1,  1,  0, -1]])

In [24]:
Ab[2,:] = Ab[2,:] + Ab[1,:]

In [25]:
Ab

matrix([[ 4, -2,  1,  8],
        [ 1, -1,  0,  7],
        [ 2,  0,  0,  6]])

In [26]:
Ab[2,:] = Ab[2,:]/2
Ab

matrix([[ 4, -2,  1,  8],
        [ 1, -1,  0,  7],
        [ 1,  0,  0,  3]])

In [27]:
Ab[1,:] = Ab[2,:] - Ab[1,:]
Ab

matrix([[ 4, -2,  1,  8],
        [ 0,  1,  0, -4],
        [ 1,  0,  0,  3]])

In [29]:
Ab[0,:] = Ab[0,:] - (4*Ab[2,:]) + (2*Ab[1,:])
Ab

matrix([[  0,   0,   1, -12],
        [  0,   1,   0,  -4],
        [  1,   0,   0,   3]])

In [35]:
Ab = np.matrix([
        [  0,   0,   1, -12],
        [  0,   1,   0,  -4],
        [  1,   0,   0,   3]
])
Ab

matrix([[  0,   0,   1, -12],
        [  0,   1,   0,  -4],
        [  1,   0,   0,   3]])

In [36]:
temp = Ab[2,:].copy()
Ab[2,:] = Ab[0,:]
Ab[0,:] = temp
Ab

matrix([[  1,   0,   0,   3],
        [  0,   1,   0,  -4],
        [  0,   0,   1, -12]])

In [38]:
A = np.matrix([
    [4,-2,1],
    [1,1,1],
    [9,3,1]
])

b = np.matrix([
    [8],
    [-13],
    [3]
])

In [39]:
A

matrix([[ 4, -2,  1],
        [ 1,  1,  1],
        [ 9,  3,  1]])

In [40]:
b

matrix([[  8],
        [-13],
        [  3]])

In [41]:
# x = inverse(A)*b
inv_A = np.linalg.inv(A)

In [42]:
inv_A

matrix([[ 0.06666667, -0.16666667,  0.1       ],
        [-0.26666667,  0.16666667,  0.1       ],
        [ 0.2       ,  1.        , -0.2       ]])

In [43]:
t1 = np.dot(A,inv_A)
print(t1)

[[ 1.00000000e+00  0.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00 -2.77555756e-17]
 [-2.77555756e-17  0.00000000e+00  1.00000000e+00]]


In [45]:
t2 = np.dot(inv_A,A)
print(t2)

[[ 1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-8.32667268e-17  1.00000000e+00 -2.77555756e-17]
 [ 1.66533454e-16 -1.66533454e-16  1.00000000e+00]]


In [46]:
# Inverse matrix method
x = np.dot(inv_A,b)
x

matrix([[  3.],
        [ -4.],
        [-12.]])

In [47]:
A

matrix([[ 4, -2,  1],
        [ 1,  1,  1],
        [ 9,  3,  1]])

In [48]:
Ax1 = A.copy()
Ax1

matrix([[ 4, -2,  1],
        [ 1,  1,  1],
        [ 9,  3,  1]])

In [49]:
Ax1[:,0] = b
Ax1

matrix([[  8,  -2,   1],
        [-13,   1,   1],
        [  3,   3,   1]])

In [50]:
# Cramer's Rule

x1 = np.linalg.det(Ax1)/np.linalg.det(A)
print(x1)

2.9999999999999996


In [51]:
Ax2 = A.copy()
Ax2[:,1] = b
x2 = np.linalg.det(Ax2)/np.linalg.det(A)
print(x2)

-4.000000000000003


In [52]:
Ax3 = A.copy()
Ax3[:,2] = b
x3 = np.linalg.det(Ax3)/np.linalg.det(A)
print(x3)

-12.0


In [69]:
A = np.matrix([
    [4.0,-2.0,1.0],
    [1.0,1.0,1.0],
    [9.0,3.0,1.0]
])

b = np.matrix([
    [8.0],
    [-13.0],
    [3.0]
])

In [70]:
Ab = np.append(A,b,axis=1)
print(Ab)

[[  4.  -2.   1.   8.]
 [  1.   1.   1. -13.]
 [  9.   3.   1.   3.]]


In [71]:
def fwd_elim_v1(Ab):
    Abx = Ab.copy()
    [nr, nc] = Abx.shape
    
    # step 1: eliminate the 1st terms of row index 1:N-1
    for r in range(1,nr):
        row_factor = Abx[r,0]/Abx[0,0]
        Abx[r,:] = Abx[r,:] - (Abx[0,:]*row_factor)
    #end for
    
    print(Abx)
#end function
    

In [72]:
fwd_elim_v1(Ab)

[[  4.    -2.     1.     8.  ]
 [  0.     1.5    0.75 -15.  ]
 [  0.     7.5   -1.25 -15.  ]]


In [79]:
def fwd_elim_v2(Ab):
    Abx = Ab.copy()
    [nr, nc] = Abx.shape
    
    # step 1: eliminate the 1st terms of row index 1:N-1
    for r in range(1,nr):
        row_factor = Abx[r,0]/Abx[0,0]
        Abx[r,:] = Abx[r,:] - (Abx[0,:]*row_factor)
    #end for
    
    # step 2: eliminate the 2nd terms of row index 2:N-1
    for r in range(2,nr):
        row_factor = Abx[r,1]/Abx[1,1]
        Abx[r,:] = Abx[r,:] - (Abx[1,:]*row_factor)
    #end for
    
    print(Abx)
    return Abx
#end function

In [74]:
fwd_elim_v2(Ab)

[[  4.    -2.     1.     8.  ]
 [  0.     1.5    0.75 -15.  ]
 [  0.     0.    -5.    60.  ]]


In [83]:
def back_sub_v1(Ab_re):
    Abx = Ab_re.copy()
    [nr, nc] = Abx.shape
    
    x = np.zeros(3)
    
    x[2] = Abx[nr-1,nc-1]/Abx[nr-1,nc-2]
    print(x[2])
    
#end function
    

In [76]:
x = np.zeros(3)
x

array([0., 0., 0.])

In [78]:
Ab

matrix([[  4.,  -2.,   1.,   8.],
        [  1.,   1.,   1., -13.],
        [  9.,   3.,   1.,   3.]])

In [80]:
Ab_re = fwd_elim_v2(Ab)

[[  4.    -2.     1.     8.  ]
 [  0.     1.5    0.75 -15.  ]
 [  0.     0.    -5.    60.  ]]


In [81]:
Ab_re

matrix([[  4.  ,  -2.  ,   1.  ,   8.  ],
        [  0.  ,   1.5 ,   0.75, -15.  ],
        [  0.  ,   0.  ,  -5.  ,  60.  ]])

In [82]:
back_sub_v1(Ab_re)

-12.0


In [84]:
def back_sub_v2(Ab_re):
    Abx = Ab_re.copy()
    [nr, nc] = Abx.shape
    
    x = np.zeros(3)
    
    # Step 1: Find x[2]
    x[2] = Abx[nr-1,nc-1]/Abx[nr-1,nc-2]
    print(x[2])
    
    # Step 2: Find x[1]
    x[1] = (Abx[nr-2,nc-1] - Abx[nr-2,nc-2]*x[2])/Abx[nr-2,nc-3]
    print(x[1])
    
#end function

In [85]:
back_sub_v2(Ab_re)

-12.0
-4.0


In [86]:
Ab_re

matrix([[  4.  ,  -2.  ,   1.  ,   8.  ],
        [  0.  ,   1.5 ,   0.75, -15.  ],
        [  0.  ,   0.  ,  -5.  ,  60.  ]])

In [87]:
def back_sub_v3(Ab_re):
    Abx = Ab_re.copy()
    [nr, nc] = Abx.shape
    
    x = np.zeros(3)
    
    # Step 1: Find x[2]
    x[2] = Abx[nr-1,nc-1]/Abx[nr-1,nc-2]
    print(x[2])
    
    # Step 2: Find x[1]
    x[1] = (Abx[nr-2,nc-1] - Abx[nr-2,nc-2]*x[2])/Abx[nr-2,nc-3]
    print(x[1])
    
    # Step 3: Fix x[0]
    x[0] = (Abx[nr-3,nc-1] - Abx[nr-3,nc-2]*x[2] - Abx[nr-3,nc-3]*x[1])/Abx[nr-3,nc-4]
    print(x[0])
    
#end function

In [88]:
back_sub_v3(Ab_re)

-12.0
-4.0
3.0
