In [1]:
import numpy as np
import math

In [2]:
M = np.matrix([
    [4,-2,1,8],
    [1,1,1,-13],
    [9,3,1,3]
])

In [3]:
eq4 = M[0,:]-M[1,:]
print(eq4)

[[ 3 -3  0 21]]


In [4]:
eq4 = eq4 / 3
print(eq4)

[[ 1. -1.  0.  7.]]


In [5]:
M = np.append(M,eq4,axis=0)
print(M)

[[  4.  -2.   1.   8.]
 [  1.   1.   1. -13.]
 [  9.   3.   1.   3.]
 [  1.  -1.   0.   7.]]


In [6]:
eq5 = M[2,:] - M[1,:]
print(eq5)

[[ 8.  2.  0. 16.]]


In [7]:
eq5 = eq5 / 2
print(eq5)

[[4. 1. 0. 8.]]


In [8]:
M = np.append(M,eq5,axis=0)
print(M)

[[  4.  -2.   1.   8.]
 [  1.   1.   1. -13.]
 [  9.   3.   1.   3.]
 [  1.  -1.   0.   7.]
 [  4.   1.   0.   8.]]


In [11]:
eq6 = eq4 + eq5
# eq6 = M[3,:] + M[4,:]
print(eq6)

[[ 5.  0.  0. 15.]]


In [12]:
eq6 = eq6 / 5
print(eq6)

[[1. 0. 0. 3.]]


In [13]:
M = np.append(M,eq6,axis=0)
print(M)

[[  4.  -2.   1.   8.]
 [  1.   1.   1. -13.]
 [  9.   3.   1.   3.]
 [  1.  -1.   0.   7.]
 [  4.   1.   0.   8.]
 [  1.   0.   0.   3.]]


In [14]:
eq7 = eq6 - eq4
print(eq7)

[[ 0.  1.  0. -4.]]


In [15]:
M = np.append(M,eq7,axis = 0)
print(M)

[[  4.  -2.   1.   8.]
 [  1.   1.   1. -13.]
 [  9.   3.   1.   3.]
 [  1.  -1.   0.   7.]
 [  4.   1.   0.   8.]
 [  1.   0.   0.   3.]
 [  0.   1.   0.  -4.]]


In [16]:
eq8 = M[1,:] - M[5,:] - M[6,:]
# eq8 = M[1,:] - eq6 - eq7
print(eq8)

[[  0.   0.   1. -12.]]


In [17]:
M = np.append(M,eq8,axis=0)
print(M)

[[  4.  -2.   1.   8.]
 [  1.   1.   1. -13.]
 [  9.   3.   1.   3.]
 [  1.  -1.   0.   7.]
 [  4.   1.   0.   8.]
 [  1.   0.   0.   3.]
 [  0.   1.   0.  -4.]
 [  0.   0.   1. -12.]]


In [3]:
A = np.matrix([
    [4,-2,1],
    [1,1,1],
    [9,3,1]
])
A

matrix([[ 4, -2,  1],
        [ 1,  1,  1],
        [ 9,  3,  1]])

In [4]:
b = np.matrix([
    [8],
    [-13],
    [3]
])
b

matrix([[  8],
        [-13],
        [  3]])

In [20]:
inv_A = np.linalg.inv(A)
print(inv_A)

[[ 0.06666667 -0.16666667  0.1       ]
 [-0.26666667  0.16666667  0.1       ]
 [ 0.2         1.         -0.2       ]]


In [21]:
x = np.dot(inv_A,b)
print(x)

[[  3.]
 [ -4.]
 [-12.]]


In [22]:
# Cramer's rule

Ax1 = A.copy()
Ax1[:,0] = b
print(Ax1)

[[  8  -2   1]
 [-13   1   1]
 [  3   3   1]]


In [23]:
x1 = np.linalg.det(Ax1)/np.linalg.det(A)
print(x1)

2.9999999999999996


In [24]:
print(round(x1))

3.0


In [25]:
Ax2 = A.copy()
Ax2[:,1] = b
print(Ax2)

[[  4   8   1]
 [  1 -13   1]
 [  9   3   1]]


In [26]:
x2 = np.linalg.det(Ax2)/np.linalg.det(A)
print(x2)
print(round(x2))

-4.000000000000003
-4.0


In [27]:
Ax3 = A.copy()
Ax3[:,2] = b
print(Ax3)

[[  4  -2   8]
 [  1   1 -13]
 [  9   3   3]]


In [28]:
x3 = np.linalg.det(Ax3)/np.linalg.det(A)
print(x3)
print(round(x3))

-12.0
-12.0


In [5]:
A = A * 1.0
print(A)

[[ 4. -2.  1.]
 [ 1.  1.  1.]
 [ 9.  3.  1.]]


In [6]:
b = b * 1.0
print(b)

[[  8.]
 [-13.]
 [  3.]]


In [7]:
Ab = np.append(A,b,axis=1)
print(Ab)

[[  4.  -2.   1.   8.]
 [  1.   1.   1. -13.]
 [  9.   3.   1.   3.]]


In [49]:
# Gauss's elimination

# Iteration 1: work on the first column
# Make reference to the top row
# update all rows after the top row by removing the first term
# of each row.

In [50]:
# Iteration #1

# row 2
row_factor = Ab[1,0]/Ab[0,0]
Ab[1,:] = Ab[1,:] - Ab[0,:]*row_factor
print(Ab)

# row 3
row_factor = Ab[2,0]/Ab[0,0]
Ab[2,:] = Ab[2,:] - Ab[0,:]*row_factor
print(Ab)

[[  4.    -2.     1.     8.  ]
 [  0.     1.5    0.75 -15.  ]
 [  9.     3.     1.     3.  ]]
[[  4.    -2.     1.     8.  ]
 [  0.     1.5    0.75 -15.  ]
 [  0.     7.5   -1.25 -15.  ]]


In [51]:
# Iteration #2
# Remove the coefficient of the 2nd variable
# Row 3 will be affected

# row 3
row_factor = Ab[2,1]/Ab[1,1]
Ab[2,:] = Ab[2,:] - Ab[1,:]*row_factor
print(Ab)

[[  4.    -2.     1.     8.  ]
 [  0.     1.5    0.75 -15.  ]
 [  0.     0.    -5.    60.  ]]


In [3]:
def fwd_elim(Ab):
    Ab_re = Ab.copy()
    [nr,nc] = Ab_re.shape
    
    # set i as the Iteration index
    for i in range(1,nr):
        print('Iteration #{}: '.format(i))
        # set r as the row index to work on
        for r in range(i,nr):
            print('  working on row index {}'.format(r))
            # iteration index represent the order of the variable that we want to eliminate
            row_factor = Ab_re[r,i-1]/Ab_re[i-1,i-1]
            Ab_re[r,:] = Ab_re[r,:] - Ab_re[i-1,:]*row_factor
        #end for r
    #end for i
    print(Ab_re)
    return Ab_re
#end function

In [72]:
Ab = np.append(A,b,axis=1)
Ab = Ab * 1.0
print(Ab)

[[  4.  -2.   1.   8.]
 [  1.   1.   1. -13.]
 [  9.   3.   1.   3.]]


In [73]:
Ab_re = fwd_elim(Ab)

Iteration #1: 
  working on row index 1
  working on row index 2
Iteration #2: 
  working on row index 2
[[  4.    -2.     1.     8.  ]
 [  0.     1.5    0.75 -15.  ]
 [  0.     0.    -5.    60.  ]]


In [74]:
print(Ab)

[[  4.  -2.   1.   8.]
 [  1.   1.   1. -13.]
 [  9.   3.   1.   3.]]


In [75]:
print(Ab_re)

[[  4.    -2.     1.     8.  ]
 [  0.     1.5    0.75 -15.  ]
 [  0.     0.    -5.    60.  ]]


In [76]:
x3 = Ab_re[2,3]/Ab_re[2,2]
print(x3)

-12.0


In [77]:
x2 = (Ab_re[1,3]-(Ab_re[1,2]*x3))/Ab_re[1,1]
print(x2)

-4.0


In [78]:
x1 = (Ab_re[0,3]-(Ab_re[0,1]*x2 + Ab_re[0,2]*x3))/Ab_re[0,0]
print(x1)

3.0


In [38]:
def back_sub(Ab_re):
    [nr,nc] = Ab_re.shape
    # nr will represent the total number of variables that we have to find
    # create x to hold calculated values
    x = np.empty(nr)
    
    # v is the variable iterator (index)
    for v in range(nr-1,-1,-1):
        print('v = {}'.format(v))
        # x_v = (constant - (sum_of_products between coeff_i and x_i))/coeff of x_v
        # where i > v
        
        sum_of_products = 0
        for i in range(v+1,nr):
            print('  i = {}'.format(i))
            product = Ab_re[v,i]*x[i]
            sum_of_products = sum_of_products + product
        #end for i
        
        x[v] = (Ab_re[v,nc-1] - sum_of_products)/Ab_re[v,v]
    #end for v
    print(x)
    return x

#end function

In [86]:
x = back_sub(Ab_re)

v = 2
v = 1
  i = 2
v = 0
  i = 1
  i = 2
[  3.  -4. -12.]


In [2]:
A = np.matrix([
    [4,-2,1],
    [1,1,1],
    [9,3,1]
])
A = A * 1.0
b = np.matrix([
    [8],
    [-13],
    [3]
])
b = b * 1.0
Ab = np.append(A,b,axis=1)
print(Ab)

[[  4.  -2.   1.   8.]
 [  1.   1.   1. -13.]
 [  9.   3.   1.   3.]]


In [4]:
Ab_re = fwd_elim(Ab)
print(Ab_re)

Iteration #1: 
  working on row index 1
  working on row index 2
Iteration #2: 
  working on row index 2
[[  4.    -2.     1.     8.  ]
 [  0.     1.5    0.75 -15.  ]
 [  0.     0.    -5.    60.  ]]
[[  4.    -2.     1.     8.  ]
 [  0.     1.5    0.75 -15.  ]
 [  0.     0.    -5.    60.  ]]


In [29]:
def fwd_elim_recurse(Ab):
    [nr,nc] = Ab.shape
    Abx = Ab.copy()
    
    # partial pivoting
    # (students work on this)
    # (rearrange the rows)

    if (nr == 1):
        # don't do anything
        pass
    else:
        # r is the iterator for the rows whose first element removed
        for r in range(1,nr):
            row_factor = Abx[r,0]/Abx[0,0]
            Abx[r,:] = Abx[r,:] - Abx[0,:]*row_factor
        #end for
        print(Abx)
        # define the red box to be send to the next recursion
        red_box = Abx[1:nr,1:nc].copy()
        print(red_box)
        temp = fwd_elim_recurse(red_box)
        Abx[1:nr,1:nc] = temp
    #end if
    return Abx
#end function

In [16]:
print(Ab)

[[  4.  -2.   1.   8.]
 [  1.   1.   1. -13.]
 [  9.   3.   1.   3.]]


In [17]:
fwd_elim_recurse(Ab)

[[  4.    -2.     1.     8.  ]
 [  0.     1.5    0.75 -15.  ]
 [  0.     7.5   -1.25 -15.  ]]
[[  1.5    0.75 -15.  ]
 [  7.5   -1.25 -15.  ]]
[[  1.5    0.75 -15.  ]
 [  0.    -5.    60.  ]]
[[-5. 60.]]


matrix([[  4.  ,  -2.  ,   1.  ,   8.  ],
        [  0.  ,   1.5 ,   0.75, -15.  ],
        [  0.  ,   0.  ,  -5.  ,  60.  ]])

In [18]:
def fwd_elim_recurse_pt(Ab):
    [nr,nc] = Ab.shape

    if (nr == 1):
        # don't do anything
        pass
    else:
        # r is the iterator for the rows whose first element removed
        for r in range(1,nr):
            row_factor = Ab[r,0]/Ab[0,0]
            Ab[r,:] = Ab[r,:] - Ab[0,:]*row_factor
        #end for
        print(Ab)
        # define the red box to be send to the next recursion
        print(Ab[1:nr,1:nc])
        fwd_elim_recurse_pt(Ab[1:nr,1:nc])
    #end if
#end function

In [19]:
print(Ab)

[[  4.  -2.   1.   8.]
 [  1.   1.   1. -13.]
 [  9.   3.   1.   3.]]


In [20]:
fwd_elim_recurse_pt(Ab)

[[  4.    -2.     1.     8.  ]
 [  0.     1.5    0.75 -15.  ]
 [  0.     7.5   -1.25 -15.  ]]
[[  1.5    0.75 -15.  ]
 [  7.5   -1.25 -15.  ]]
[[  1.5    0.75 -15.  ]
 [  0.    -5.    60.  ]]
[[-5. 60.]]


In [21]:
print(Ab)

[[  4.    -2.     1.     8.  ]
 [  0.     1.5    0.75 -15.  ]
 [  0.     0.    -5.    60.  ]]


In [22]:
Ab = np.array([
    [0,2,5,1],
    [2,1,1,1],
    [3,1,0,2]
])
Ab = Ab*1.0
print(Ab)

[[0. 2. 5. 1.]
 [2. 1. 1. 1.]
 [3. 1. 0. 2.]]


In [23]:
A = Ab[:,0:3]
print(A)
b = Ab[:,3]
print(b)

[[0. 2. 5.]
 [2. 1. 1.]
 [3. 1. 0.]]
[1. 1. 2.]


In [24]:
b.shape

(3,)

In [25]:
inv_A = np.linalg.inv(A)
inv_A

array([[ -1.,   5.,  -3.],
       [  3., -15.,  10.],
       [ -1.,   6.,  -4.]])

In [27]:
x = np.dot(inv_A,b)
print(x)

[-2.  8. -3.]


In [28]:
print(Ab)

[[0. 2. 5. 1.]
 [2. 1. 1. 1.]
 [3. 1. 0. 2.]]


In [30]:
Ab_re = fwd_elim_recurse(Ab)

[[  0.   2.   5.   1.]
 [ nan -inf -inf -inf]
 [ nan -inf -inf -inf]]
[[-inf -inf -inf]
 [-inf -inf -inf]]
[[-inf -inf -inf]
 [ nan  nan  nan]]
[[nan nan]]


c:\program files\python37\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in double_scalars
  # This is added back by InteractiveShellApp.init_path()
c:\program files\python37\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in multiply
  if sys.path[0] == '':
c:\program files\python37\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in double_scalars
  # This is added back by InteractiveShellApp.init_path()


In [35]:
Ab = np.array([
    [0,2,5,1],
    [2,1,1,1],
    [3,1,0,2]
])
Ab = Ab*1.0
print(Ab)

[[0. 2. 5. 1.]
 [2. 1. 1. 1.]
 [3. 1. 0. 2.]]


In [32]:
# faulty swap assignment
temp = Ab[0,:]
Ab[2,:] = temp
Ab[0,:] = Ab[2,:]
print(Ab)

[[0. 2. 5. 1.]
 [2. 1. 1. 1.]
 [0. 2. 5. 1.]]


In [36]:
# correct swap assignment
temp = Ab[0,:].copy()
Ab[0,:] = Ab[2,:].copy()
Ab[2,:] = temp
print(Ab)

[[3. 1. 0. 2.]
 [2. 1. 1. 1.]
 [0. 2. 5. 1.]]


In [37]:
Ab_re = fwd_elim_recurse(Ab)
print(Ab_re)

[[ 3.          1.          0.          2.        ]
 [ 0.          0.33333333  1.         -0.33333333]
 [ 0.          2.          5.          1.        ]]
[[ 0.33333333  1.         -0.33333333]
 [ 2.          5.          1.        ]]
[[ 0.33333333  1.         -0.33333333]
 [ 0.         -1.          3.        ]]
[[-1.  3.]]
[[ 3.          1.          0.          2.        ]
 [ 0.          0.33333333  1.         -0.33333333]
 [ 0.          0.         -1.          3.        ]]


In [39]:
x = back_sub(Ab_re)
print(x)

v = 2
v = 1
  i = 2
v = 0
  i = 1
  i = 2
[-2.  8. -3.]
[-2.  8. -3.]


In [41]:
Ab = np.array([
    [0,2,5,1],
    [2,1,1,1],
    [3,1,0,2]
])
Ab = Ab*1.0
print(Ab)

[[0. 2. 5. 1.]
 [2. 1. 1. 1.]
 [3. 1. 0. 2.]]


In [42]:
temp = Ab[:,0].copy()
Ab[:,0] = Ab[:,2].copy()
Ab[:,2] = temp
print(Ab)

[[5. 2. 0. 1.]
 [1. 1. 2. 1.]
 [0. 1. 3. 2.]]


In [43]:
A = Ab[:,0:3]
print(A)
b = Ab[:,3]
print(b)

[[5. 2. 0.]
 [1. 1. 2.]
 [0. 1. 3.]]
[1. 1. 2.]


In [44]:
x = np.dot(np.linalg.inv(A),b)
print(x)

[-3.  8. -2.]
