In [1]:
import numpy as np
import math

In [3]:
M = np.matrix([
    [4,-2,1,8],
    [1,1,1,-13],
    [9,3,1,3]
])

In [4]:
M

matrix([[  4,  -2,   1,   8],
        [  1,   1,   1, -13],
        [  9,   3,   1,   3]])

In [5]:
M[1,1]

1

In [6]:
M[0,0]

4

In [8]:
M[2,1:3]

matrix([[3, 1]])

In [9]:
M[2,:]

matrix([[9, 3, 1, 3]])

In [10]:
M[:,1]

matrix([[-2],
        [ 1],
        [ 3]])

In [15]:
# first row - second row ---> eq4
eq4 = M[0,:] - M[1,:]

In [16]:
eq4

matrix([[ 3, -3,  0, 21]])

In [17]:
eq5 = M[2,:] - M[1,:]
eq5

matrix([[ 8,  2,  0, 16]])

In [18]:
eq4 = eq4/3
eq4

matrix([[ 1., -1.,  0.,  7.]])

In [19]:
eq5 = eq5/2
eq5

matrix([[4., 1., 0., 8.]])

In [20]:
eq6 = eq4 + eq5
eq6

matrix([[ 5.,  0.,  0., 15.]])

In [21]:
eq6 = eq6/5

In [22]:
eq6

matrix([[1., 0., 0., 3.]])

In [23]:
eq4

matrix([[ 1., -1.,  0.,  7.]])

In [24]:
eq7 = eq6 - eq4
eq7

matrix([[ 0.,  1.,  0., -4.]])

In [26]:
M[1,:]

matrix([[  1,   1,   1, -13]])

In [27]:
eq8 = M[1,:] - eq6 - eq7
eq8

matrix([[  0.,   0.,   1., -12.]])

In [30]:
R = eq6
R

matrix([[1., 0., 0., 3.]])

In [31]:
R = np.append(R,eq7, axis=0)
R

matrix([[ 1.,  0.,  0.,  3.],
        [ 0.,  1.,  0., -4.]])

In [32]:
R = np.append(R, eq8, axis=0)
R

matrix([[  1.,   0.,   0.,   3.],
        [  0.,   1.,   0.,  -4.],
        [  0.,   0.,   1., -12.]])

In [42]:
A = np.matrix([
    [4,-2,1],
    [1,1,1],
    [9,3,1]
])

B = np.matrix([
    [8],[-13],[3]
])

In [43]:
A

matrix([[ 4, -2,  1],
        [ 1,  1,  1],
        [ 9,  3,  1]])

In [44]:
B

matrix([[  8],
        [-13],
        [  3]])

In [45]:
B.shape

(3, 1)

In [46]:
A.shape

(3, 3)

In [47]:
inv_A = np.linalg.inv(A)
inv_A

matrix([[ 0.06666667, -0.16666667,  0.1       ],
        [-0.26666667,  0.16666667,  0.1       ],
        [ 0.2       ,  1.        , -0.2       ]])

In [48]:
np.dot(A,inv_A)

matrix([[ 1.00000000e+00,  0.00000000e+00, -1.11022302e-16],
        [ 0.00000000e+00,  1.00000000e+00, -2.77555756e-17],
        [-2.77555756e-17,  0.00000000e+00,  1.00000000e+00]])

In [49]:
np.dot(inv_A, A)

matrix([[ 1.00000000e+00, -1.11022302e-16,  0.00000000e+00],
        [-8.32667268e-17,  1.00000000e+00, -2.77555756e-17],
        [ 1.66533454e-16, -1.66533454e-16,  1.00000000e+00]])

In [50]:
x = np.dot(inv_A,B)
x

matrix([[  3.],
        [ -4.],
        [-12.]])

In [51]:
A

matrix([[ 4, -2,  1],
        [ 1,  1,  1],
        [ 9,  3,  1]])

In [52]:
B

matrix([[  8],
        [-13],
        [  3]])

In [53]:
# Cramer's Rule

Ax1 = A.copy()
Ax1[:,0] = B
Ax1

matrix([[  8,  -2,   1],
        [-13,   1,   1],
        [  3,   3,   1]])

In [54]:
# Cramer's Rule
x1 = np.linalg.det(Ax1)/np.linalg.det(A)
x1

2.9999999999999996

In [55]:
Ax2 = A.copy()
Ax2[:,1] = B
Ax2

matrix([[  4,   8,   1],
        [  1, -13,   1],
        [  9,   3,   1]])

In [56]:
# Cramer's Rule
x2 = np.linalg.det(Ax2)/np.linalg.det(A)
x2

-4.000000000000003

In [57]:
Ax3 = A.copy()
Ax3[:,2] = B
Ax3

matrix([[  4,  -2,   8],
        [  1,   1, -13],
        [  9,   3,   3]])

In [58]:
# Cramer's Rule
x3 = np.linalg.det(Ax3)/np.linalg.det(A)
x3

-12.0

In [63]:
# Gauss Elimination
M = np.matrix([
    [4.0, -2.0, 1.0, 8.0],
    [1.0, 1.0, 1.0, -13.0],
    [9.0, 3.0, 1.0, 3.0]
])

In [64]:
Ab = M.copy()
Ab

matrix([[  4.,  -2.,   1.,   8.],
        [  1.,   1.,   1., -13.],
        [  9.,   3.,   1.,   3.]])

In [65]:
# Gauss elimination: (iteration 1: i = 1)
# Step 1: Remove the 1st coefficient out of row 2 - N

# row 2
row_factor = Ab[1,0]/Ab[0,0]
Ab[1,:] = Ab[1,:] - row_factor*Ab[0,:]
Ab

matrix([[  4.  ,  -2.  ,   1.  ,   8.  ],
        [  0.  ,   1.5 ,   0.75, -15.  ],
        [  9.  ,   3.  ,   1.  ,   3.  ]])

In [66]:
# row 3
row_factor = Ab[2,0]/Ab[0,0]
Ab[2,:] = Ab[2,:] - row_factor*Ab[0,:]
Ab

matrix([[  4.  ,  -2.  ,   1.  ,   8.  ],
        [  0.  ,   1.5 ,   0.75, -15.  ],
        [  0.  ,   7.5 ,  -1.25, -15.  ]])

In [67]:
# Next iteration (i = 2)
# remove the 2nd term starting from row 3 to N

# row 3
row_factor = Ab[2,1]/Ab[1,1]
Ab[2,:] = Ab[2,:] - row_factor*Ab[1,:]
Ab

matrix([[  4.  ,  -2.  ,   1.  ,   8.  ],
        [  0.  ,   1.5 ,   0.75, -15.  ],
        [  0.  ,   0.  ,  -5.  ,  60.  ]])

In [84]:
def fwd_elim_3x3_v1(Ab):
    [nr,nc] = Ab.shape
    Ab_re = Ab.copy()
    
    # this is a hard-coded function written to support 3x4 matrix only
    # Gauss elimination: (iteration 1: i = 1)
    # Step 1: Remove the 1st coefficient out of row 2 - N
    
    # row 2
    row_factor = Ab_re[1,0]/Ab_re[0,0]
    print('row 2: row_factor = {}'.format(row_factor))
    Ab_re[1,:] = Ab_re[1,:] - row_factor*Ab_re[0,:]
    print(Ab_re)
    
    # row 3
    row_factor = Ab_re[2,0]/Ab_re[0,0]
    print('row 3: row_factor = {}'.format(row_factor))
    Ab_re[2,:] = Ab_re[2,:] - row_factor*Ab_re[0,:]
    
    return Ab_re
#end function

In [85]:
Ab

matrix([[  4.,  -2.,   1.,   8.],
        [  1.,   1.,   1., -13.],
        [  9.,   3.,   1.,   3.]])

In [86]:
M

matrix([[  4.,  -2.,   1.,   8.],
        [  1.,   1.,   1., -13.],
        [  9.,   3.,   1.,   3.]])

In [87]:
Ab = M.copy()

In [88]:
fwd_elim_3x3_v1(Ab)

row 2: row_factor = 0.25
[[  4.    -2.     1.     8.  ]
 [  0.     1.5    0.75 -15.  ]
 [  9.     3.     1.     3.  ]]
row 3: row_factor = 2.25


matrix([[  4.  ,  -2.  ,   1.  ,   8.  ],
        [  0.  ,   1.5 ,   0.75, -15.  ],
        [  0.  ,   7.5 ,  -1.25, -15.  ]])

In [91]:
def fwd_elim_3x3_v2(Ab):
    [nr,nc] = Ab.shape
    Ab_re = Ab.copy()
    
    # this is a hard-coded completed function written to support 3x4 matrix only
    # Gauss elimination: (iteration 1: i = 1)
    # Step 1: Remove the 1st coefficient out of row 2 - N
    
    # row 2
    row_factor = Ab_re[1,0]/Ab_re[0,0]
    # print('row 2: row_factor = {}'.format(row_factor))
    Ab_re[1,:] = Ab_re[1,:] - row_factor*Ab_re[0,:]
    # print(Ab_re)
    
    # row 3
    row_factor = Ab_re[2,0]/Ab_re[0,0]
    # print('row 3: row_factor = {}'.format(row_factor))
    Ab_re[2,:] = Ab_re[2,:] - row_factor*Ab_re[0,:]
    
    # Next iteration (i = 2)
    # remove the 2nd term starting from row 3 to N

    # row 3
    row_factor = Ab_re[2,1]/Ab_re[1,1]
    Ab_re[2,:] = Ab_re[2,:] - row_factor*Ab_re[1,:]
    
    return Ab_re
#end function

In [92]:
Ab = M.copy()
fwd_elim_3x3_v2(Ab)

matrix([[  4.  ,  -2.  ,   1.  ,   8.  ],
        [  0.  ,   1.5 ,   0.75, -15.  ],
        [  0.  ,   0.  ,  -5.  ,  60.  ]])

In [102]:
def fwd_elim(Ab):
    [nr,nc] = Ab.shape
    Ab_re = Ab.copy()
    
    # this is a hard-coded completed function written to support 3x4 matrix only
    # Gauss elimination: (iteration 1: i = 1)
    # Step 1: Remove the 1st coefficient out of row 2 - N
    
    for i in range(1,nr):
        print('Iteration #{}:'.format(i))
        # r is row_index running from i+1 until nr
        for r in range(i+1,nr+1):
            print('Working on row #{}'.format(r))
            row_factor = Ab_re[r-1,i-1]/Ab_re[i-1,i-1]
            Ab_re[r-1,:] = Ab_re[r-1,:] - row_factor*Ab_re[i-1,:]
            print(Ab_re)
        #end for
    #end
    
    '''
    
    # row 2
    row_factor = Ab_re[1,0]/Ab_re[0,0]
    # print('row 2: row_factor = {}'.format(row_factor))
    Ab_re[1,:] = Ab_re[1,:] - row_factor*Ab_re[0,:]
    # print(Ab_re)
    
    # row 3
    row_factor = Ab_re[2,0]/Ab_re[0,0]
    # print('row 3: row_factor = {}'.format(row_factor))
    Ab_re[2,:] = Ab_re[2,:] - row_factor*Ab_re[0,:]
    
    # Next iteration (i = 2)
    # remove the 2nd term starting from row 3 to N

    # row 3
    row_factor = Ab_re[2,1]/Ab_re[1,1]
    Ab_re[2,:] = Ab_re[2,:] - row_factor*Ab_re[1,:]

    '''
    
    return Ab_re
#end function

In [104]:
Ab = M.copy()
Ab_re = fwd_elim(Ab)

Iteration #1:
Working on row #2
[[  4.    -2.     1.     8.  ]
 [  0.     1.5    0.75 -15.  ]
 [  9.     3.     1.     3.  ]]
Working on row #3
[[  4.    -2.     1.     8.  ]
 [  0.     1.5    0.75 -15.  ]
 [  0.     7.5   -1.25 -15.  ]]
Iteration #2:
Working on row #3
[[  4.    -2.     1.     8.  ]
 [  0.     1.5    0.75 -15.  ]
 [  0.     0.    -5.    60.  ]]


In [105]:
Ab_re

matrix([[  4.  ,  -2.  ,   1.  ,   8.  ],
        [  0.  ,   1.5 ,   0.75, -15.  ],
        [  0.  ,   0.  ,  -5.  ,  60.  ]])

In [106]:
x3 = Ab_re[2,3]/Ab_re[2,2]
x3

-12.0

In [110]:
x2 = (Ab_re[1,3]-(Ab_re[1,2]*x3))/Ab_re[1,1]
x2

-4.0

In [111]:
x1 = (Ab_re[0,3]-(Ab_re[0,1]*x2 + Ab_re[0,2]*x3))/Ab_re[0,0]
x1

3.0

In [18]:
def backsub(Ab_re):
    [nr,nc] = Ab.shape
    x = np.empty(nr)
    
    x[nr-1] = Ab_re[nr-1,nc-1]/Ab_re[nr-1,nr-1]
    print('x[{}] = {}'.format(nr-1,x[nr-1]))
    
    for r in range(nr-2,-1,-1):
        # range (1,-1,-1) will give i = 1,0
        # sum_of_products = sum of products of coeff of x[i+1] and x[i+1]
        # before this
        sum_of_products = 0
        for c in range(r+1, nr):
            product = Ab_re[r,c]*x[c]
            sum_of_products = sum_of_products + product
        #end for
        x[r] = (Ab_re[r,nc-1] - sum_of_products)/Ab_re[r,r]
    #end for
    return x
#end function

In [137]:
x = np.empty(3)
x

array([ 3.,  4., 12.])

In [138]:
backsub(Ab_re)

x[2] = -12.0


array([  3.,  -4., -12.])

In [2]:
A = np.matrix([
    [4,-2,1],
    [1,1,1],
    [9,3,1]
])
A = A*1.0

B = np.matrix([
    [8],[-13],[3]
])
B = B*1.0

In [3]:
Ab = np.append(A,B,axis=1)
print(Ab)

[[  4.  -2.   1.   8.]
 [  1.   1.   1. -13.]
 [  9.   3.   1.   3.]]


In [13]:
def fwd_elim_recurse(Ab):
    [nr,nc] = Ab.shape
    
    # partial or complete pivoting
    # 1. check whether we have 0 in the element Ab[0,0]
    # 2.    if Ab[0,0] == 0, then
    # 3.        swap rows or columns
    #           Task 5: swap the rows such that the coefficients in the first column
    #           are ordered from highest to lowest
    #
    
    Abx = Ab.copy() # to make sure that we don't touch Ab
    print('Abx = ')
    print(Abx)
    
    if (nr == 1):
        # then don't do anything
        pass
    else:
        # For each iteration, remove the front coefficient from row 2 to row N
        for r in range(1,nr):
            print('working on row index {}'.format(r))
            row_factor = Abx[r,0]/Abx[0,0]
            Abx[r,:] = Abx[r,:] - Abx[0,:]*row_factor
        #end for
        red_box = Abx[1:nr,1:nc]
        transformed_red_box = fwd_elim_recurse(red_box)
        Abx[1:nr,1:nc] = transformed_red_box
    #end if
    
    return(Abx)

#end function

In [14]:
Ab_re = fwd_elim_recurse(Ab)

Abx = 
[[  4.  -2.   1.   8.]
 [  1.   1.   1. -13.]
 [  9.   3.   1.   3.]]
working on row index 1
working on row index 2
Abx = 
[[  1.5    0.75 -15.  ]
 [  7.5   -1.25 -15.  ]]
working on row index 1
Abx = 
[[-5. 60.]]


In [15]:
print(Ab_re)

[[  4.    -2.     1.     8.  ]
 [  0.     1.5    0.75 -15.  ]
 [  0.     0.    -5.    60.  ]]


In [20]:
backsub(Ab_re)

x[2] = -12.0


array([  3.,  -4., -12.])

In [21]:
A = np.array([
    [0,2,5],
    [2,1,1],
    [3,1,0]
])
A = A*1.0
b = np.array([
    [1],
    [1],
    [2]
])
b = b*1.0
Ab = np.append(A,b,axis=1)
print(Ab)

[[0. 2. 5. 1.]
 [2. 1. 1. 1.]
 [3. 1. 0. 2.]]


In [22]:
inv_A = np.linalg.inv(A)
x = np.dot(inv_A,b)
print(x)

[[-2.]
 [ 8.]
 [-3.]]


In [23]:
Ab_re = fwd_elim_recurse(Ab)

Abx = 
[[0. 2. 5. 1.]
 [2. 1. 1. 1.]
 [3. 1. 0. 2.]]
working on row index 1
working on row index 2
Abx = 
[[-inf -inf -inf]
 [-inf -inf -inf]]
working on row index 1
Abx = 
[[nan nan]]


c:\program files\python37\lib\site-packages\ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in double_scalars
  
c:\program files\python37\lib\site-packages\ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in multiply
  from ipykernel import kernelapp as app
c:\program files\python37\lib\site-packages\ipykernel_launcher.py:14: RuntimeWarning: invalid value encountered in double_scalars
  


In [24]:
print(Ab)

[[0. 2. 5. 1.]
 [2. 1. 1. 1.]
 [3. 1. 0. 2.]]


In [25]:
temp = Ab[0,:].copy()
Ab[0,:] = Ab[2,:].copy()
Ab[2,:] = temp
print(Ab)

[[3. 1. 0. 2.]
 [2. 1. 1. 1.]
 [0. 2. 5. 1.]]


In [26]:
Ab_re = fwd_elim_recurse(Ab)

Abx = 
[[3. 1. 0. 2.]
 [2. 1. 1. 1.]
 [0. 2. 5. 1.]]
working on row index 1
working on row index 2
Abx = 
[[ 0.33333333  1.         -0.33333333]
 [ 2.          5.          1.        ]]
working on row index 1
Abx = 
[[-1.  3.]]


In [27]:
print(Ab_re)

[[ 3.          1.          0.          2.        ]
 [ 0.          0.33333333  1.         -0.33333333]
 [ 0.          0.         -1.          3.        ]]


In [28]:
backsub(Ab_re)

x[2] = -3.0000000000000018


array([-2.,  8., -3.])

In [29]:
print(Ab)

[[3. 1. 0. 2.]
 [2. 1. 1. 1.]
 [0. 2. 5. 1.]]


In [30]:
A = np.array([
    [0,2,5],
    [2,1,1],
    [3,1,0]
])
A = A*1.0
b = np.array([
    [1],
    [1],
    [2]
])
b = b*1.0
Ab = np.append(A,b,axis=1)
print(Ab)

[[0. 2. 5. 1.]
 [2. 1. 1. 1.]
 [3. 1. 0. 2.]]


In [31]:
temp = Ab[:,0].copy()
Ab[:,0] = Ab[:,1].copy()
Ab[:,1] = temp
print(Ab)

[[2. 0. 5. 1.]
 [1. 2. 1. 1.]
 [1. 3. 0. 2.]]


In [32]:
Ab_re = fwd_elim_recurse(Ab)

Abx = 
[[2. 0. 5. 1.]
 [1. 2. 1. 1.]
 [1. 3. 0. 2.]]
working on row index 1
working on row index 2
Abx = 
[[ 2.  -1.5  0.5]
 [ 3.  -2.5  1.5]]
working on row index 1
Abx = 
[[-0.25  0.75]]


In [33]:
backsub(Ab_re)

x[2] = -3.0


array([ 8., -2., -3.])