In [2]:
import numpy as np
import math

<h2>TASK 1</h2>

In [3]:
M = np.matrix([
    [2,1,1,10],
    [3,2,3,18],
    [1,4,9,16]
])

In [4]:
eq4  = 2*M[0,:]-M[1,:]
print(eq4)

[[ 1  0 -1  2]]


In [5]:
M = np.append(M,eq4,axis=0)
print(M)

[[ 2  1  1 10]
 [ 3  2  3 18]
 [ 1  4  9 16]
 [ 1  0 -1  2]]


In [6]:
eq5  = M[2,:]-eq4
print(eq5)

[[ 0  4 10 14]]


In [7]:
eq5 = eq5/2
print(eq5)

[[0. 2. 5. 7.]]


In [8]:
M = np.append(M,eq5,axis=0)
print(M)

[[ 2.  1.  1. 10.]
 [ 3.  2.  3. 18.]
 [ 1.  4.  9. 16.]
 [ 1.  0. -1.  2.]
 [ 0.  2.  5.  7.]]


In [9]:
eq6 = M[1,:]-3*eq4
print(eq6)

[[ 0.  2.  6. 12.]]


In [10]:
eq6 = eq6/2
print(eq6)

[[0. 1. 3. 6.]]


In [11]:
M = np.append(M,eq6,axis=0)
print(M)

[[ 2.  1.  1. 10.]
 [ 3.  2.  3. 18.]
 [ 1.  4.  9. 16.]
 [ 1.  0. -1.  2.]
 [ 0.  2.  5.  7.]
 [ 0.  1.  3.  6.]]


In [12]:
eq7 = 2*eq6-eq5
print(eq7)

[[0. 0. 1. 5.]]


In [13]:
M = np.append(M,eq7,axis=0)
print(M)

[[ 2.  1.  1. 10.]
 [ 3.  2.  3. 18.]
 [ 1.  4.  9. 16.]
 [ 1.  0. -1.  2.]
 [ 0.  2.  5.  7.]
 [ 0.  1.  3.  6.]
 [ 0.  0.  1.  5.]]


In [14]:
eq8 = eq6-3*eq7
print(eq8)

[[ 0.  1.  0. -9.]]


In [15]:
M = np.append(M,eq8,axis=0)
print(M)

[[ 2.  1.  1. 10.]
 [ 3.  2.  3. 18.]
 [ 1.  4.  9. 16.]
 [ 1.  0. -1.  2.]
 [ 0.  2.  5.  7.]
 [ 0.  1.  3.  6.]
 [ 0.  0.  1.  5.]
 [ 0.  1.  0. -9.]]


In [16]:
eq9 = eq4 + eq7
print(eq9)

[[1. 0. 0. 7.]]


In [17]:
M = np.append(M,eq9,axis=0)
print(M)

[[ 2.  1.  1. 10.]
 [ 3.  2.  3. 18.]
 [ 1.  4.  9. 16.]
 [ 1.  0. -1.  2.]
 [ 0.  2.  5.  7.]
 [ 0.  1.  3.  6.]
 [ 0.  0.  1.  5.]
 [ 0.  1.  0. -9.]
 [ 1.  0.  0.  7.]]


<h2>TASK 2</h2>

In [18]:
A = np.matrix([
    [2,1,1],
    [3,2,3],
    [1,4,9]
])
A

matrix([[2, 1, 1],
        [3, 2, 3],
        [1, 4, 9]])

In [19]:
B = np.matrix([
    [10],
    [18],
    [16]
])
B

matrix([[10],
        [18],
        [16]])

In [20]:
inv_A = np.linalg.inv(A)
print(inv_A)

[[-3.   2.5 -0.5]
 [12.  -8.5  1.5]
 [-5.   3.5 -0.5]]


In [21]:
X = np.dot(inv_A,B)
print(X)

[[ 7.]
 [-9.]
 [ 5.]]


<h2>TASK 3</h2>

In [22]:
def fwd_elim_recurse(AB):
    [nr,nc] = AB.shape
    ABx = AB.copy()
    
    if(nr == 1):
        pass
    else:
        # r is the iterator for the rows which first element removed
        for r in range(1,nr):
            row_factor = ABx[r,0]/ABx[0,0]
            ABx[r,:] = ABx[r,:] - ABx[0,:]*row_factor
        # end for
        red_box = ABx[1:nr,1:nc].copy()
        temp = fwd_elim_recurse(red_box)
        ABx[1:nr,1:nc] = temp
    # end if
    return ABx
# end func

In [23]:
def back_sub(AB_re):
    [nr,nc ] = AB_re.shape
    # nr will represent the total nimber of variables that we have to find
    # create x to hold calculated values
    x = np.empty(nr)
    
    # v is the variable iterator (index)
    for v in range(nr-1,-1,-1):
        # x = constant - (sum_of_products between coeff_i and x_i)/coeff of x_v
        # where i > v
        sum_of_products = 0
        for i in range(v+1,nr):
            product = AB_re[v,i]*x[i]
            sum_of_products = sum_of_products + product
        # end for
        
        x[v] = (AB_re[v,nc-1] - sum_of_products)/AB_re[v,v]
        
    # end for
    print(x)
    return x
# end func

In [23]:
A = A *1.0
B = B*1.0

AB = np.append(A,B,axis=1)
print(AB)

[[ 2.  1.  1. 10.]
 [ 3.  2.  3. 18.]
 [ 1.  4.  9. 16.]]


In [24]:
AB_re = fwd_elim_recurse(AB)
AB_re

matrix([[  2. ,   1. ,   1. ,  10. ],
        [  0. ,   0.5,   1.5,   3. ],
        [  0. ,   0. ,  -2. , -10. ]])

In [25]:
x = back_sub(AB_re)

[ 7. -9.  5.]


<h2>TASK 4</h2>

In [26]:
def cramer(X,Y,n):
    
    for i in range(0,n):
        X1 = X.copy()
        X1[:,i] = Y
        print(X1)
        xx1 = np.linalg.det(X1)/np.linalg.det(X)
        print(round(xx1)) 
    # end for
# end func

In [27]:
A1 = np.matrix([
    [2,-5],
    [3,1]
])

B1 = np.matrix([
    [15],
    [31]
])

cramer(A1,B1,len(A1))

[[15 -5]
 [31  1]]
10.0
[[ 2 15]
 [ 3 31]]
1.0


In [28]:
A2 = np.matrix([
    [2,1,1],
    [3,2,3],
    [1,4,9]
])

B2 = np.matrix([
    [10],
    [18],
    [16]
])

cramer(A2,B2,len(A2))

[[10  1  1]
 [18  2  3]
 [16  4  9]]
7.0
[[ 2 10  1]
 [ 3 18  3]
 [ 1 16  9]]
-9.0
[[ 2  1 10]
 [ 3  2 18]
 [ 1  4 16]]
5.0


In [29]:
A3 = np.matrix([
    [1,2,1,4],
    [2,0,4,3],
    [4,2,2,1],
    [-3,1,3,2]
])

B3 = np.matrix([
    [13],
    [28],
    [20],
    [6]
])

cramer(A3,B3,len(A3))

[[13  2  1  4]
 [28  0  4  3]
 [20  2  2  1]
 [ 6  1  3  2]]
3.0
[[ 1 13  1  4]
 [ 2 28  4  3]
 [ 4 20  2  1]
 [-3  6  3  2]]
-1.0
[[ 1  2 13  4]
 [ 2  0 28  3]
 [ 4  2 20  1]
 [-3  1  6  2]]
4.0
[[ 1  2  1 13]
 [ 2  0  4 28]
 [ 4  2  2 20]
 [-3  1  3  6]]
2.0
