In [207]:
import numpy as np
A = np.matrix([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [208]:
#Task5

def is_square(A):
    (nrows, ncoln) = A.shape
    if(nrows == ncoln):
        print('{} is a square matrix.'.format(A))
    else:
        print('{} is not a square matrix.'.format(A))
        
(is_square(A))

[[1 2 3]
 [4 5 6]
 [7 8 9]] is a square matrix.


In [209]:
#Task5

def is_symmetrical(A):
    (nrows, ncoln) = A.shape
    for i  in range(0, nrows):
        for j in range(0, ncoln):
            if(A[i,j] == A[j,i]):
                return True
            
if(is_symmetrical(A)):
    print('{} is a symmetrical matrix.'.format(A))
else:
    print('{} is not a symmetrical matrix.'.format(A))



[[1 2 3]
 [4 5 6]
 [7 8 9]] is a symmetrical matrix.


In [210]:
#Task5

def is_diagonal(A):
    (nrows,ncoln) = A.shape
    for i  in range(0, nrows):
        for j in range(0, ncoln):
            if(i != j and A[i,j] != 0):
                return True
    return False

if(True):
    print('{} is a not diagonal matrix'.format(A))
else:
    print('{} is a diagonal matrix'.format(A))

[[1 2 3]
 [4 5 6]
 [7 8 9]] is a not diagonal matrix


In [211]:
#Task5
def is_identity(A):
    (nrows, ncoln) = A.shape
    for i  in range(0, nrows):
        for j in range(0, ncoln):
            if(i != j and int(A[i,j]) != 0):
                return False
                break
            if(i == j and int(A[i,j]) != 1):
                return False
                break
if(is_identity(A)):
    print('{} is a identity matrix'.format(A))
else:
    print('{} is a not identity matrix'.format(A))   


[[1 2 3]
 [4 5 6]
 [7 8 9]] is a not identity matrix


In [212]:
#Task5

def is_zero(A):
    zr = True
    [nrows, ncoln] = A.shape
    for i in range (0, nrows):
        for j in range (0, ncoln):
            if(A[i, j] != 0):
                zr = False
                
    if(zr): 
        print('{} is a zero matrix'.format(A))
    else:
        print('{} is not a zero matrix'.format(A))
        
is_zero(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]] is not a zero matrix


In [213]:
#Task5
def transpose(A):
    (nrows,ncoln) = A.shape
    temp = np.zeros((nrows,ncoln), dtype=int)
    for i  in range(0, nrows):
        for j in range(0, ncoln):
            temp[j,i] = A[i,j]
            
    return temp
print('The transpose of A is')
transpose(A)

The transpose of A is


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [214]:
#Task6

A = np.matrix([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.matrix([
    [2,3],
    [4,5],
    [6,7]
])

def is_square_matrix(A):
    (nrow_A,ncol_A) = A.shape
    if (nrow_A == ncol_A):
        return True
    else:
        return False
    
def dot_product(A,B):
    (nrows_A,ncoln_A) = A.shape
    (nrows_B,ncoln_B) = B.shape
    print('A is a ({}x{}) matrix'.format(nrows_A,ncoln_A))
    print('B is a ({}x{}) matrix'.format(nrows_B,ncoln_B))

    if (ncoln_A == nrows_B):
        C = np.zeros((nrows_A,ncoln_B))
        (nrows_C,ncoln_C) = C.shape
        i = 0
        j = 0
        k = 0
        while i < nrows_C:
            j = 0
            while j < ncoln_C:
                #print('Calculating element ({},{})'.format(i,j))
                product_sum = 0
                k = 0
                while k < ncoln_A:
                    e_product = A[i,k] * B[k,j]
                    product_sum = product_sum + e_product
                    #print('Multiplying A({},{}) and B({},{}): {} x {} = {}'.format(i,k,k,j,A[i,k],B[k,j],e_product))
                    k += 1
                #print('product_sum = {}'.format(product_sum))
                C[i,j] = product_sum
                j += 1
            i += 1
    else:
        print('Error: dot_product: ncol_A is not the same as nrow_B')
        return
    return C

(nrows_A,ncoln_A) = A.shape
(nrows_B,ncoln_B) = B.shape

# C = np.zeros((nrow_A,ncol_B))
# C[0][0] = 1
# C[1][1] = 2
# print(C)

AB = dot_product(A,B)
print(AB)
print('\n')
BA = dot_product(B,A)
print(BA)

A is a (2x3) matrix
B is a (3x2) matrix
[[28. 34.]
 [64. 79.]]


A is a (3x2) matrix
B is a (2x3) matrix
[[14. 19. 24.]
 [24. 33. 42.]
 [34. 47. 60.]]


In [215]:
import numpy as np

C = ([
    [1,3,2],
    [4,2,1],
    [5,2,1]
])

In [216]:
#Task7

def minordet(A,x,y):
    mi_d = []
    for i in range(len(A)):
        check = []
        for j in range(len(A)):
            
            if i != y and j != x:
                check.append(A[j][i]) 
                

        if check:
            mi_d.append(check)
    return mi_d

def deter(A):
    det = 0
    if(len(A) == 1):
        det = A[0,0]
    else:
        for i in range(0,len(A)):
            m = minor_request(A,0,i)
            temp = (m[0][0] * m[1][1]) - (m[0][1] * m[1][0])
            det = det + (-1)**(i) * A[0][i] * temp
    return det  

print('The determinant of C is {}'.format(deter(C)))

The determinant of C is -1


In [217]:
D = ([
    [1,2,3,4],
    [4,3,2,1],
    [2,3,4,1],
    [3,4,1,2]
])

In [218]:
#Task8

def deter(A):
    det = 0
    if(len(A)==1):
        det = A[0][0]
    else:
        for i in range(0,len(A)):
            m = minordet(A,0,i)
            det = det + (-1)**(i) *A[0][i] * deter(m)
    return det

def minor(A):  
    mat = []
    for i in range(len(A)):
        for j in range(len(A)):
            x = deter(minordet(A,i,j))
            mat.append(x)
    return np.array(mat).reshape(len(A),len(A))

print('The minor of D is')
minor(D)


The minor of D is


array([[  4,  16,   4, -24],
       [-44, -36,  -4,   4],
       [-20, -20,  20,  20],
       [ 20,  40,  20,   0]])

In [219]:
#Task8

def cofactor(A):
    cofac = minor(A)
    for i in range(len(A)):
        for j in range(len(A)):
            cofac[i][j] = (-1)**(i+j) * cofac[i][j]

    return cofac

print('The cofactor of D is')
cofactor(D)

The cofactor of D is


array([[  4, -16,   4,  24],
       [ 44, -36,   4,   4],
       [-20,  20,  20, -20],
       [-20,  40, -20,   0]])

In [220]:
#Task8

def adjoint(A):
    return transpose(cofactor(A))

print('The adjoint of D is')
adjoint(D)

The adjoint of D is


array([[  4,  44, -20, -20],
       [-16, -36,  20,  40],
       [  4,   4,  20, -20],
       [ 24,   4, -20,   0]])

In [221]:
#Task8

def inverse(A):
    inverse = []
    adj = adjoint(A)
    det = deter(A)
    for i in range(len(A)):
            temp = []
            for j in range(len(A)):
                temp.append(adj[i][j] / det)
            inverse.append(temp)
    return np.array(inverse)    

print('The inverse of D is')
inverse(D)

The inverse of D is


array([[ 0.05,  0.55, -0.25, -0.25],
       [-0.2 , -0.45,  0.25,  0.5 ],
       [ 0.05,  0.05,  0.25, -0.25],
       [ 0.3 ,  0.05, -0.25,  0.  ]])