In [60]:
import numpy as np
import math

In [61]:
#Task1
A = np.matrix([
    [2, 1, 1, 10],
    [3, 2, 3, 18],
    [1, 4, 9, 16]
])
print(A)

[[ 2  1  1 10]
 [ 3  2  3 18]
 [ 1  4  9 16]]


In [62]:
a = 2*A[0,:]-A[1,:]
print(a)
A = np.append(A,a,axis=0)
print(A)

[[ 1  0 -1  2]]
[[ 2  1  1 10]
 [ 3  2  3 18]
 [ 1  4  9 16]
 [ 1  0 -1  2]]


In [63]:
b  = A[2,:]-a
print(b)
b = b/2
print(b)
A = np.append(A,b,axis=0)
print(A)

[[ 0  4 10 14]]
[[0. 2. 5. 7.]]
[[ 2.  1.  1. 10.]
 [ 3.  2.  3. 18.]
 [ 1.  4.  9. 16.]
 [ 1.  0. -1.  2.]
 [ 0.  2.  5.  7.]]


In [64]:
c = A[1,:]-3*a
print(c)
c = c/2
print(c)
A = np.append(A,c,axis=0)
print(A)

[[ 0.  2.  6. 12.]]
[[0. 1. 3. 6.]]
[[ 2.  1.  1. 10.]
 [ 3.  2.  3. 18.]
 [ 1.  4.  9. 16.]
 [ 1.  0. -1.  2.]
 [ 0.  2.  5.  7.]
 [ 0.  1.  3.  6.]]


In [65]:
d = 2*c-b
print(d)
A = np.append(A,d,axis=0)
print(A)

[[0. 0. 1. 5.]]
[[ 2.  1.  1. 10.]
 [ 3.  2.  3. 18.]
 [ 1.  4.  9. 16.]
 [ 1.  0. -1.  2.]
 [ 0.  2.  5.  7.]
 [ 0.  1.  3.  6.]
 [ 0.  0.  1.  5.]]


In [66]:
e = c-3*d
print(e)
A = np.append(A,e,axis=0)
print(A)

[[ 0.  1.  0. -9.]]
[[ 2.  1.  1. 10.]
 [ 3.  2.  3. 18.]
 [ 1.  4.  9. 16.]
 [ 1.  0. -1.  2.]
 [ 0.  2.  5.  7.]
 [ 0.  1.  3.  6.]
 [ 0.  0.  1.  5.]
 [ 0.  1.  0. -9.]]


In [67]:
f = a + d
print(f)
A = np.append(A,f,axis=0)
print(A)

[[1. 0. 0. 7.]]
[[ 2.  1.  1. 10.]
 [ 3.  2.  3. 18.]
 [ 1.  4.  9. 16.]
 [ 1.  0. -1.  2.]
 [ 0.  2.  5.  7.]
 [ 0.  1.  3.  6.]
 [ 0.  0.  1.  5.]
 [ 0.  1.  0. -9.]
 [ 1.  0.  0.  7.]]


In [68]:
#Task2
A = np.matrix([
    [2,1,1],
    [3,2,3],
    [1,4,9]
])
print(A)

B = np.matrix([
    [10],
    [18],
    [16]
])
print(B)

[[2 1 1]
 [3 2 3]
 [1 4 9]]
[[10]
 [18]
 [16]]


In [69]:
inv_A = np.linalg.inv(A)
print(inv_A)

X = np.dot(inv_A,B)
print(X)

[[-3.   2.5 -0.5]
 [12.  -8.5  1.5]
 [-5.   3.5 -0.5]]
[[ 7.]
 [-9.]
 [ 5.]]


In [70]:
def fwd_elim_recurse(AB):
    [nr,nc] = AB.shape
    ABx = AB.copy()
    
    if(nr == 1):
        pass
    else:
        for r in range(1,nr):
            row_factor = ABx[r,0]/ABx[0,0]
            ABx[r,:] = ABx[r,:] - ABx[0,:]*row_factor
        red_box = ABx[1:nr,1:nc].copy()
        temp = fwd_elim_recurse(red_box)
        ABx[1:nr,1:nc] = temp
    return ABx

In [71]:
def back_sub(Ab_re):
    [nr,nc] = Ab_re.shape
    x = np.empty(nr)
    
    for v in range(nr-1,-1,-1):
        sum_of_products = 0
        for i in range(v+1,nr):
            product = Ab_re[v,i]*x[i]
            sum_of_products = sum_of_products + product
        x[v] = (Ab_re[v,nc-1] - sum_of_products)/Ab_re[v,v]
    print(x)
    return x

In [72]:
A = A *1.0
B = B*1.0

AB = np.append(A,B,axis=1)
print(AB)

[[ 2.  1.  1. 10.]
 [ 3.  2.  3. 18.]
 [ 1.  4.  9. 16.]]


In [73]:
AB_re = fwd_elim_recurse(AB)
print(AB_re)

[[  2.    1.    1.   10. ]
 [  0.    0.5   1.5   3. ]
 [  0.    0.   -2.  -10. ]]


In [74]:
x = back_sub(AB_re)

[ 7. -9.  5.]


In [75]:
#Task4
def cramer(X,Y,n):
    for i in range(0,n):
        X1 = X.copy()
        X1[:,i] = Y
        print(X1)
        xx1 = np.linalg.det(X1)/np.linalg.det(X)
        print(round(xx1)) 


In [76]:
A1 = np.matrix([
    [2,-5],
    [3,1]
])

B1 = np.matrix([
    [15],
    [31]
])

cramer(A1,B1,len(A1))

[[15 -5]
 [31  1]]
10.0
[[ 2 15]
 [ 3 31]]
1.0


In [77]:
A2 = np.matrix([
    [2,1,1],
    [3,2,3],
    [1,4,9]
])

B2 = np.matrix([
    [10],
    [18],
    [16]
])

cramer(A2,B2,len(A2))

[[10  1  1]
 [18  2  3]
 [16  4  9]]
7.0
[[ 2 10  1]
 [ 3 18  3]
 [ 1 16  9]]
-9.0
[[ 2  1 10]
 [ 3  2 18]
 [ 1  4 16]]
5.0


In [79]:
A3 = np.matrix([
    [1,2,1,4],
    [2,0,4,3],
    [4,2,2,1],
    [-3,1,3,2]
])

B3 = np.matrix([
    [13],
    [28],
    [20],
    [6]
])

cramer(A3,B3,len(A3))


[[13  2  1  4]
 [28  0  4  3]
 [20  2  2  1]
 [ 6  1  3  2]]
3.0
[[ 1 13  1  4]
 [ 2 28  4  3]
 [ 4 20  2  1]
 [-3  6  3  2]]
-1.0
[[ 1  2 13  4]
 [ 2  0 28  3]
 [ 4  2 20  1]
 [-3  1  6  2]]
4.0
[[ 1  2  1 13]
 [ 2  0  4 28]
 [ 4  2  2 20]
 [-3  1  3  6]]
2.0
