In [1]:
import math
print('e^2 = {}'.format(math.e**(0.2)))

e^2 = 1.2214027581601699


In [2]:
def factorial(n):
    #innitialize product
    product = 1
    for i in range(1,n+1):
        product = product * i
    #end for
    return(product)
#end function


In [3]:
print(factorial(4))

24


In [4]:
output = 1 + 0.2 + (0.2*0.2)/factorial(2) + (0.2**0.2**0.2)/factorial(3)
print(output)

1.2719098178497297


In [5]:
true_value = math.e**0.2
print(true_value)

1.2214027581601699


In [6]:
true_error = true_value - output
print(true_error)
true_error_pct = abs((true_value - output)/true_value)*100
print(true_error_pct)

-0.05050705968955982
4.13516830153879


In [7]:
#find e^0.2
sum = 0
x = 0.2
for i in range(0,6):
    sum = sum + (x**i)/factorial(i)
print(sum)

1.2214026666666666


In [8]:
print(math.e**0.2)

1.2214027581601699


In [9]:
#find e^0.2 using stopping criterion

output = 0
prev_output = 0
x = 0.2
p = 5
es = 0.5*(10**(2-p))
ea = 100
i = 0

print('es = {}'.format(es))
while(ea>es):
    output = output + (x**i)/factorial(i)
    i+=1
    ea = abs((output - prev_output)/output) * 100
    prev_output = output
    print('output = {} ea = {}'.format(output,ea))
#end while

print('final output = {}'.format(output))

es = 0.0005
output = 1.0 ea = 100.0
output = 1.2 ea = 16.666666666666664
output = 1.22 ea = 1.6393442622950833
output = 1.2213333333333334 ea = 0.10917030567686205
output = 1.2214 ea = 0.005458217346214125
output = 1.2214026666666666 ea = 0.0002183282171696027
final output = 1.2214026666666666


In [10]:
4.7/math.e

1.729033373505779

In [11]:
math.e

2.718281828459045

In [12]:
def f(int x):
    return x**2 - 3*x -2

SyntaxError: invalid syntax (<ipython-input-12-08ab18995ceb>, line 1)

In [13]:
#Import the necessary packages and modules
import matplotlib.pyplot as plt
import numpy as np

#Prepare the data 
x = np.linspace(-10,10,101)

print(x)

y = f(x)

print(y)

#Plot the data
plt.plot(x,y,label='linear')

#Add a legend
plt.legend()

#Show the plot
plt.show()

[-10.   -9.8  -9.6  -9.4  -9.2  -9.   -8.8  -8.6  -8.4  -8.2  -8.   -7.8
  -7.6  -7.4  -7.2  -7.   -6.8  -6.6  -6.4  -6.2  -6.   -5.8  -5.6  -5.4
  -5.2  -5.   -4.8  -4.6  -4.4  -4.2  -4.   -3.8  -3.6  -3.4  -3.2  -3.
  -2.8  -2.6  -2.4  -2.2  -2.   -1.8  -1.6  -1.4  -1.2  -1.   -0.8  -0.6
  -0.4  -0.2   0.    0.2   0.4   0.6   0.8   1.    1.2   1.4   1.6   1.8
   2.    2.2   2.4   2.6   2.8   3.    3.2   3.4   3.6   3.8   4.    4.2
   4.4   4.6   4.8   5.    5.2   5.4   5.6   5.8   6.    6.2   6.4   6.6
   6.8   7.    7.2   7.4   7.6   7.8   8.    8.2   8.4   8.6   8.8   9.
   9.2   9.4   9.6   9.8  10. ]


NameError: name 'f' is not defined

In [1]:
#task4?

import numpy as np
A = np.matrix([
    [1,2],
    [3,4]
])
B = np.matrix([
    [1,0,0],
    [0,1,0]
])
C = np.matrix([
    [2,-1,0],
    [1,2,1,],
    [4,1,3]
])
D = np.matrix([
    [2,5],
    [7,3]
])

print(A)
print(B)
print(C)
print(D)

[[1 2]
 [3 4]]
[[1 0 0]
 [0 1 0]]
[[ 2 -1  0]
 [ 1  2  1]
 [ 4  1  3]]
[[2 5]
 [7 3]]


In [ ]:
A + D

In [ ]:
A + C #A=2*2 C=3*3

In [ ]:
# is_square

def is_square(A):
    (nrows, ncoln) = A.shape
    print('number of rows = {} number of columns = {}'.format(nrows, ncoln))
    if(nrows == ncoln):
        return True
    else:
        return False

In [ ]:
if(is_square(D)):
    print('{} is a square matrix.'.format(D))
else:
    print('{} is not a square matrix'.format(D))

In [3]:
def is_symmetric(A):
    (nrows,ncoln) = A.shape
    for i  in range(0, nrows):
        for j in range(0, ncoln):
            #print('A[{},{}] = {} '.format(i,j,A[i,j]))
            if(A[i,j]==A[j,i]):
                pass
            else:
                return False
    return True

In [4]:
S = np.matrix([
    [3,-2,4],
    [-2,6,2],
    [4,2,3]
])

In [5]:
print(is_symmetric(S))

True


In [ ]:
D

In [6]:
def is_diagonal(A):
    (nrows,ncoln) = A.shape
    for i  in range(0, nrows):
        for j in range(0, ncoln):
            if((i!=j) and (A[i,j]!= 0)):
                return False
            else:
                pass
    return True

In [7]:
M = np.matrix([
    [1,0,0],
    [0,8,0],
    [0,0,4]
])

In [8]:
print(is_diagonal(M))

True


In [ ]:
D

In [ ]:
print(is_diagonal(S))

In [17]:
U = np.matrix([
    [1,1,-1,-2],
    [0,2,1,3],
    [0,1,1,3],
    [0,2,1,4]
])

In [18]:
np.linalg.inv(U)

matrix([[ 1., -1.,  3., -1.],
        [ 0.,  1., -1.,  0.],
        [ 0.,  2.,  2., -3.],
        [ 0., -1.,  0.,  1.]])

In [19]:
np.linalg.det(U)

1.0